#[cfg(desktop)]
use super::dns_manager::DnsConfigMode;
#[cfg(desktop)]
use super::route_manager::RouteMode;
use bytesize::ByteSize;
use clap::Parser;
use lightway_app_utils::args::{
    Cipher, ConfigFormat, ConnectionType, Duration, KeyShare, LogLevel, NonZeroDuration,
};
use lightway_core::{AuthMethod, MAX_OUTSIDE_MTU, Version};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::OnceLock;
use std::time::Duration as StdDuration;
use std::{net::Ipv4Addr, path::PathBuf};
use struct_patch::{Patch, Substrate};

static CLI_OPTIONS: OnceLock<ConfigPatch> = OnceLock::new();

const DEFAULT_SNDBUF: ByteSize = ByteSize::mib(8);
const DEFAULT_RCVBUF: ByteSize = ByteSize::mib(8);

// NOTE
// The cli argument and options all set to ConfigPatch, which is generated by
// Patch derive, do NOT set defualts in the clap macros, and let all default
// values follow the Rust convention in Default trait, such that we are able
// to serialized out any kind of configure from the Config::default(), such
// that our library will be nice and easy to further do integrations.
#[derive(Clone, Debug, PartialEq, Deserialize, JsonSchema, Serialize, Patch, Substrate)]
#[patch(attribute(derive(Clone, Deserialize, Parser)))]
#[patch(attribute(command(about = "A lightway client")))]
pub struct Config {
    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(
        doc = "Generate configure for single server in the format to path from `-c, --config-file`"
    ))]
    #[serde(skip_serializing)]
    #[schemars(skip)]
    pub generate: ConfigFormat,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = "Config File to load"))]
    #[serde(skip_serializing)]
    #[schemars(skip)]
    pub config_file: PathBuf,

    /// Servers to attempt to connect to. Configuration is only supported in
    /// config file, not command line or environment variable
    #[patch(attribute(clap(skip)))]
    #[serde(default)]
    #[serde(skip_serializing)]
    #[schemars(skip)]
    servers: Vec<ConnectionConfig>,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = r#"Server to connect to in `<hostname>:<port>` format
    Only used if `servers` is empty"#))]
    /// socket address, ex: 127.0.0.1:27690
    pub server: String,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = r#"Connection mode
    Only used if `servers` is empty"#))]
    pub mode: ConnectionType,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"Server domain name
    Only used if `servers` is empty"#))]
    pub server_dn: String,

    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = r#"Cipher to use for encryption
    Only used if `servers` is empty"#))]
    pub cipher: Cipher,

    #[patch(attribute(clap(long, hide = true)))]
    #[patch(attribute(doc = r#"Auth token
    If both token and user/pass are provided, token auth will
    be used. user/pass will be ignored in this case"#))]
    #[schemars(extend("format" = "password"))]
    pub token: Option<String>,

    #[patch(attribute(clap(short, long, hide = true)))]
    #[patch(attribute(doc = "Username for auth"))]
    pub user: Option<String>,

    #[patch(attribute(clap(short, long, hide = true)))]
    #[patch(attribute(doc = "Password for auth"))]
    #[schemars(extend("format" = "password"))]
    pub password: Option<String>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"CA certificate
    This can either be a path to the file, or a string starting with
    "-----BEGIN CERTIFICATE-----""#))]
    #[schemars(extend("format" = "textarea"))]
    pub ca_cert: String,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Outside (wire) MTU"))]
    pub outside_mtu: usize,

    #[patch(attribute(clap(short, long)))]
    #[patch(attribute(doc = "Tun device name to use"))]
    pub tun_name: Option<String>,

    #[cfg(linux)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Transmit queue length (txqueuelen) of the Tun device"))]
    #[schemars(extend("x-cfg" = "linux"))]
    pub tun_txqueuelen: u32,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Path to wintun.dll file (Windows only)"))]
    #[schemars(extend("x-cfg" = "windows"))]
    pub wintun_file: Option<String>,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"
    Fixed GUID for the Wintun adapter (Windows only).
    Ensures adapter creation retries reuse the same device node.
    Accepts a UUID string (e.g. "550e8400-e29b-41d4-a716-446655440000")."#))]
    pub device_guid: Option<String>,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Local IP to use in Tun device"))]
    pub tun_local_ip: Ipv4Addr,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Peer IP to use in Tun device"))]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub tun_peer_ip: Ipv4Addr,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "DNS IP to use in Tun device"))]
    pub tun_dns_ip: Ipv4Addr,

    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = "Enable Post Quantum Crypto"))]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub keyshare: KeyShare,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Interval between keepalives"))]
    #[schemars(schema_with = "lightway_app_utils::args::nonzero_duration_schema")]
    /// ex: 10s
    pub keepalive_interval: NonZeroDuration,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Keepalive timeout"))]
    #[schemars(schema_with = "lightway_app_utils::args::nonzero_duration_schema")]
    /// ex: 60s
    pub keepalive_timeout: NonZeroDuration,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable continuous Keepalive"))]
    pub keepalive_continuous: bool,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"Time it takes to trigger a tracer packet
    when we haven't received an outside packet"#))]
    #[schemars(extend("x-cfg" = "desktop"))]
    #[schemars(schema_with = "lightway_app_utils::args::nonzero_duration_schema")]
    /// ex: 10s
    pub tracer_packet_timeout: NonZeroDuration,

    // NOTE: also "Defer timeout" in mobile device
    #[patch(attribute(clap(long)))]
    #[patch(
        attribute(doc = r#"How long to wait before selecting the best connection.
    If the preferred connection connects before the timeout, it will be used immediately."#)
    )]
    #[schemars(schema_with = "lightway_app_utils::args::duration_schema")]
    /// ex: 2000ms
    pub preferred_connection_wait_interval: Duration,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"Socket send buffer size.
    Always applied for UDP.
    For TCP, only applied on macOS; skipped on Windows and Linux
    to preserve kernel buffer autotuning."#))]
    #[schemars(extend("x-cfg" = "desktop"))]
    #[schemars(schema_with = "byte_size_schema")]
    /// ex: 1.5 MiB
    pub sndbuf: ByteSize,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"Socket receive buffer size.
    Always applied for UDP.
    For TCP, only applied on macOS; skipped on Windows and Linux
    to preserve kernel buffer autotuning."#))]
    #[schemars(extend("x-cfg" = "desktop"))]
    #[schemars(schema_with = "byte_size_schema")]
    /// ex: 1.5 MiB
    pub rcvbuf: ByteSize,

    #[cfg(batch_receive)]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(
        doc = "Enable batch receive (`recvmsg_x` on macOS, `recvmmsg` on Linux/Android))"
    ))]
    #[schemars(extend("x-cfg" = "batch_receive"))]
    pub enable_batch_receive: bool,

    #[cfg(desktop)]
    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = r#"Setup of route table
    Modes:
        default: Sets up routes as specified in server, tun_local_ip, tun_peer_ip, tun_dns_ip
        noexec : Does not setup any routes
        lan    : Sets up default + additional lan routes"#))]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub route_mode: RouteMode,

    #[cfg(desktop)]
    #[patch(attribute(clap(long, num_args = 0..=1, default_missing_value = "true")))]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(
        doc = r#"Route all IPv6 traffic into a blackhole so it cannot bypass the
    tunnel. Applies to route modes default and lan."#
    ))]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub block_ipv6: bool,

    #[cfg(linux)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(clap(long)))]
    #[patch(
        attribute(doc = r#"Firewall mark (SO_MARK) applied to the outside socket.
        The tunnel's own encrypted packets carry this mark so policy routing
        rules can keep them out of the tunnel.
        In Linux networking, a fwmark of 0 represents the default unmarked state
        and will not apply SO_MARK to the socket."#)
    )]
    #[schemars(extend("x-cfg" = "linux"))]
    pub fwmark: u32,

    #[cfg(desktop)]
    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = r#"DNS configuration mode
    Modes:
        default: Sets up DNS Configuration based on target platform
        noexec : Skips DNS Configuration setup"#))]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub dns_config_mode: DnsConfigMode,

    #[patch(attribute(clap(long, value_enum)))]
    #[patch(attribute(doc = "Log level to use"))]
    pub log_level: LogLevel,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable Expresslane for [`ConnectionType::Udp`] connections"))]
    pub enable_expresslane: bool,

    #[cfg(apple)]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(
        doc = r#"Connect the outside UDP socket to the server (Apple platforms only).
    Connecting the single-peer outside socket lets sends skip the per-packet
    route lookup. The socket is re-connected on network changes."#
    ))]
    #[schemars(extend("x-cfg" = "apple"))]
    pub enable_connected_udp: bool,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Interval between Expresslane key rotations"))]
    #[schemars(schema_with = "lightway_app_utils::args::duration_schema")]
    pub expresslane_keys_rotation_interval: Duration,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable PMTU discovery for [`ConnectionType::Udp`] connections"))]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub enable_pmtud: bool,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "Base MTU to use for PMTU discovery"))]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub pmtud_base_mtu: Option<u16>,

    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable IO-uring interface for Tunnel"))]
    #[schemars(extend("x-cfg" = "linux"))]
    pub enable_tun_iouring: bool,

    // Any value more than 1024 negatively impact the throughput
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"IO-uring submission queue count.
    Only applicable when `enable_tun_iouring` is `true`"#))]
    #[schemars(extend("x-cfg" = "linux"))]
    pub iouring_entry_count: usize,

    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = r#"IO-uring sqpoll idle time.
    If non-zero use a kernel thread to perform submission queue polling.
    After the given idle time the thread will go to sleep."#))]
    #[schemars(extend("x-cfg" = "linux"))]
    #[schemars(schema_with = "lightway_app_utils::args::duration_schema")]
    /// ex: 100ms
    pub iouring_sqpoll_idle_time: Duration,

    #[patch(attribute(clap(short, long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(
        attribute(doc = r#"Enable inside packet encoding once lightway connects
    Only used if a codec is set"#)
    )]
    #[serde(alias = "enable_inside_pkt_encoding_at_connect")]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub enable_inside_pkt_encoding: bool,

    #[cfg(feature = "debug")]
    #[patch(attribute(clap(long)))]
    #[patch(attribute(doc = "File path to save wireshark keylog"))]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub keylog: Option<PathBuf>,

    #[cfg(feature = "debug")]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = "Enable TLS debug logging"))]
    #[schemars(extend("x-cfg" = "desktop"))]
    pub tls_debug: bool,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(
        attribute(doc = r#"Wintun ring buffer capacity in bytes (Windows only).
    Must be a power of two between 128KiB and 64MiB.
    Larger values improve throughput."#)
    )]
    #[schemars(schema_with = "byte_size_schema")]
    pub wintun_ring_capacity: ByteSize,

    #[cfg(windows)]
    #[patch(attribute(clap(long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = r#"Enable DPAPI encryption/decryption for config file
    Only for Windows platform"#))]
    #[schemars(extend("x-cfg" = "windows"))]
    pub enable_dpapi: bool,

    /// SNI header for TLS connections
    #[cfg(feature = "mobile")]
    #[patch(attribute(clap(skip)))]
    #[schemars(extend("x-cfg" = "mobile"))]
    pub sni_header: String,

    #[patch(attribute(clap(short, long)))]
    #[patch(empty_value = false)]
    #[patch(attribute(serde(default)))]
    #[patch(attribute(doc = r#"Accept unknown inputs with error message without quiting"#))]
    pub accept_unknowns: bool,

    /// The unknown options from config file
    #[patch(attribute(clap(skip)))]
    #[patch(attribute(serde(flatten)))]
    #[patch(skip_wrap, apply_by(std::collections::HashMap::extend))]
    pub unknowns: HashMap<String, serde_json::Value>,
}

impl Config {
    /// The number of servers
    pub fn len(&self) -> usize {
        if self.server.is_empty() {
            self.servers.len()
        } else {
            self.servers.len() + 1
        }
    }

    /// Check if there is any server setting
    pub fn is_empty(&self) -> bool {
        self.servers.is_empty() && self.server.is_empty()
    }

    /// Take out configures for servers
    /// and normalize the auth and ca of ConnectionConfig of servers
    pub fn take_servers(&mut self) -> Result<Vec<ConnectionConfig>, Error> {
        if self.servers.is_empty() {
            self.servers = vec![ConnectionConfig {
                server: self.server.clone(),
                mode: self.mode,
                server_dn: (!self.server_dn.is_empty())
                    .then(|| std::mem::take(&mut self.server_dn)),
                cipher: self.cipher,
                outside_mtu: self.outside_mtu,
                ..Default::default()
            }];
        }
        let ca_content = if check_cert_header(&self.ca_cert) {
            Some(self.ca_cert.clone())
        } else {
            // NOTE: we support a path input on desktop, we keep None if global cert is not set, and
            // it is okay to use certs for each server, thees will be checked in following loop.
            if cfg!(desktop) {
                std::fs::read_to_string(&self.ca_cert).ok()
            } else {
                None
            }
        };
        for server in self.servers.iter_mut() {
            if server.user.is_none() && server.password.is_none() && server.token.is_none() {
                server.user = self.user.clone();
                server.password = self.password.clone();
                server.token = self.token.clone();
            }

            if let Some(ref mut ca_cert) = server.ca_cert {
                if !check_cert_header(&ca_cert) {
                    // NOTE: we support a path input on desktop, but raise error if not found
                    if cfg!(desktop) {
                        *ca_cert = std::fs::read_to_string(&mut *ca_cert)
                            .map_err(|_| Error::CaFileNotFound)?;
                    } else {
                        return Err(Error::InvalidCertificate);
                    }
                }
            } else {
                if ca_content.is_none() {
                    return Err(Error::CaFileNotFound);
                }
                server.ca_cert = ca_content.clone();
            }
        }
        Ok(std::mem::take::<Vec<ConnectionConfig>>(&mut self.servers))
    }

    /// Ensure the config is validated, and alerted when there's a conflict in the settings.
    pub fn validate(&self) -> anyhow::Result<()> {
        if !self.unknowns.is_empty() {
            let fields: Vec<&str> = self.unknowns.keys().map(String::as_str).collect();
            if self.accept_unknowns {
                tracing::warn!(fields = ?fields, "unknown config fields will be ignored");
            } else {
                anyhow::bail!("unknown config fields: {:?}", fields);
            }
        }

        let mut all_servers: Vec<(&str, ConnectionType)> = self
            .servers
            .iter()
            .map(|s| (s.server.as_str(), s.mode))
            .collect();
        if !self.server.is_empty() {
            all_servers.push((self.server.as_str(), self.mode));
        }

        #[cfg(not(macos))]
        if self.sndbuf != DEFAULT_SNDBUF {
            for (server, mode) in &all_servers {
                if mode.is_tcp() {
                    tracing::warn!(
                        server,
                        "sndbuf is set but cannot be applied to this TCP connections"
                    );
                }
            }
        }
        #[cfg(not(macos))]
        if self.rcvbuf != DEFAULT_RCVBUF {
            for (server, mode) in &all_servers {
                if mode.is_tcp() {
                    tracing::warn!(
                        server,
                        "rcvbuf is set but cannot be applied to this TCP connections"
                    );
                }
            }
        }
        #[cfg(windows)]
        if let Some(guid) = &self.device_guid {
            anyhow::ensure!(
                uuid::Uuid::parse_str(guid).is_ok(),
                "device_guid must be a valid UUID (e.g. 550e8400-e29b-41d4-a716-446655440000)"
            );
        }
        if self.enable_pmtud {
            for (server, mode) in &all_servers {
                if mode.is_tcp() {
                    tracing::warn!(
                        server,
                        "enable_pmtud is set but cannot be applied to this TCP connections"
                    );
                }
            }
        }
        #[cfg(windows)]
        anyhow::ensure!(
            self.wintun_ring_capacity.0.is_power_of_two()
                && self.wintun_ring_capacity >= ByteSize::kib(128)
                && self.wintun_ring_capacity <= ByteSize::mib(64),
            "wintun_ring_capacity must be a power of two between 128KiB and 64MiB"
        );
        #[cfg(linux)]
        {
            anyhow::ensure!(self.tun_txqueuelen != 0, "tun_txqueuelen must not be 0");
            if self.tun_txqueuelen < 1000 {
                tracing::warn!(
                    txqueuelen = self.tun_txqueuelen,
                    "tun_txqueuelen is below the recommended minimum of 1000"
                );
            }
        }
        Ok(())
    }
}

impl Default for Config {
    fn default() -> Config {
        Config {
            config_file: PathBuf::default(),
            generate: ConfigFormat::Yaml,
            servers: Vec::default(),
            server: String::default(),
            mode: ConnectionType::Tcp,
            server_dn: String::new(),
            cipher: Cipher::Aes256,
            token: None,
            user: None,
            password: None,
            ca_cert: "./ca_cert.crt".to_string(),
            outside_mtu: MAX_OUTSIDE_MTU,
            #[cfg(macos)]
            tun_name: None,
            #[cfg(not(macos))]
            tun_name: Some("lightway".to_string()),
            #[cfg(linux)]
            tun_txqueuelen: 1000,
            #[cfg(windows)]
            wintun_file: None,
            #[cfg(windows)]
            device_guid: None,
            tun_local_ip: Ipv4Addr::new(100, 64, 0, 6),
            tun_peer_ip: Ipv4Addr::new(100, 64, 0, 5),
            tun_dns_ip: Ipv4Addr::new(100, 64, 0, 1),
            keyshare: KeyShare::default(),
            keepalive_interval: NonZeroDuration::from_std_duration(StdDuration::from_secs(10)),
            keepalive_timeout: NonZeroDuration::from_std_duration(StdDuration::from_secs(60)),
            keepalive_continuous: true,
            tracer_packet_timeout: NonZeroDuration::from_std_duration(StdDuration::from_secs(10)),
            preferred_connection_wait_interval: Duration::from_std_duration(
                StdDuration::from_secs(0),
            ),
            sndbuf: DEFAULT_SNDBUF,
            rcvbuf: DEFAULT_RCVBUF,
            #[cfg(batch_receive)]
            enable_batch_receive: false,
            #[cfg(desktop)]
            route_mode: RouteMode::default(),
            #[cfg(desktop)]
            block_ipv6: true,
            #[cfg(linux)]
            fwmark: 0,
            #[cfg(desktop)]
            dns_config_mode: DnsConfigMode::default(),
            log_level: LogLevel::Info,
            enable_expresslane: false,
            #[cfg(apple)]
            enable_connected_udp: false,
            expresslane_keys_rotation_interval: Duration::from_std_duration(
                lightway_core::DEFAULT_EXPRESSLANE_KEYS_ROTATION_INTERVAL,
            ),
            enable_pmtud: false,
            pmtud_base_mtu: None,
            enable_tun_iouring: false,
            iouring_entry_count: 1024,
            iouring_sqpoll_idle_time: Duration::from_std_duration(StdDuration::from_millis(100)),
            enable_inside_pkt_encoding: false,
            #[cfg(feature = "debug")]
            keylog: None,
            #[cfg(feature = "debug")]
            tls_debug: false,
            #[cfg(windows)]
            wintun_ring_capacity: ByteSize::mib(8),
            #[cfg(windows)]
            enable_dpapi: false,
            #[cfg(feature = "mobile")]
            sni_header: String::new(),
            accept_unknowns: false,
            unknowns: HashMap::new(),
        }
    }
}

#[serde_inline_default::serde_inline_default]
#[derive(
    Clone, Default, Parser, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Substrate,
)]
pub struct ConnectionConfig {
    /// Server to connect to in `<hostname>:<port>` format
    pub server: String,

    /// Connection mode
    #[serde(default)]
    pub mode: ConnectionType,

    /// Server domain name
    #[serde(default)]
    pub server_dn: Option<String>,

    /// Cipher to use for encryption
    #[serde(default)]
    pub cipher: Cipher,

    /// Username for User/Pass Auth
    #[serde(default)]
    pub user: Option<String>,

    /// Passwordfor User/Pass Auth
    #[serde(default)]
    pub password: Option<String>,

    /// Auth token
    #[serde(default)]
    pub token: Option<String>,

    /// Outside mtu
    #[serde_inline_default(MAX_OUTSIDE_MTU)]
    pub outside_mtu: usize,

    /// The CA Cert content or Path
    #[serde(default)]
    pub ca_cert: Option<String>,
}

impl ConnectionConfig {
    /// Try build auth from config
    pub fn take_auth(&mut self) -> Result<AuthMethod, Error> {
        take_auth(self.token.take(), self.user.take(), self.password.take())
    }

    /// Try build CA from ca_crt
    #[cfg(feature = "mobile")]
    pub fn load_ca(&self) -> Result<lightway_core::tls::RootCertificate<'_>, Error> {
        self.ca_cert
            .as_ref()
            .map(|ca| {
                if check_cert_header(ca) {
                    Ok(lightway_core::tls::RootCertificate::PemBuffer(
                        ca.as_bytes(),
                    ))
                } else {
                    Err(Error::InvalidCertificate)
                }
            })
            .ok_or(Error::InvalidCertificate)?
    }

    /// Try build SocketAddress from server field
    #[cfg(feature = "mobile")]
    pub fn skt_addr(&self) -> Result<std::net::SocketAddr, Error> {
        self.server
            .parse()
            .map_err(|_e| Error::InvalidSocketAddress)
    }
}

#[derive(Debug, thiserror::Error)]
#[cfg_attr(
    all(feature = "mobile", not(feature = "mobile-test")),
    derive(uniffi::Error)
)]
pub enum Error {
    /// Invalid network protocol
    #[error("Invalid network protocol")]
    #[allow(dead_code)]
    InvalidProtocol,

    /// Unable to load certificate
    #[error("Unable to load certificate")]
    InvalidCertificate,

    #[cfg(feature = "mobile")]
    /// Unable to parse the sokcet address
    #[error("Invalid Socket Address")]
    InvalidSocketAddress,

    /// Lack information to Authentication
    #[error("Insufficient information for Authentication")]
    InsufficientAuth,

    /// No such Ca file from user's input
    #[error("Ca file is absent")]
    CaFileNotFound,
}

fn take_auth(
    token: Option<String>,
    user: Option<String>,
    password: Option<String>,
) -> Result<AuthMethod, Error> {
    match (token, user, password) {
        (Some(token), _, _) => Ok(AuthMethod::VersionedToken {
            version: Version::MAXIMUM,
            token,
        }),
        (_, Some(user), Some(password)) => Ok(AuthMethod::UserPass { user, password }),
        _ => Err(Error::InsufficientAuth),
    }
}

fn check_cert_header<T: AsRef<str>>(content: T) -> bool {
    content.as_ref().starts_with("-----BEGIN CERTIFICATE-----")
}

fn byte_size_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {
    let mut schema = String::json_schema(generator);
    schema.insert(
        "pattern".into(),
        "^[0-9]+(\\.[0-9]+)?\\s*(EB|EIB|GB|GIB|KB|KIB|MB|MIB|PB|PIB|TB|TIB|eb|eib|gb|gib|kb|kib|mb|mib|pb|pib|tb|tib)$".into(),
    );
    schema
}

impl Config {
    pub fn cli_options() -> &'static ConfigPatch {
        CLI_OPTIONS.get_or_init(ConfigPatch::parse)
    }

    pub async fn load(config_file: Option<&PathBuf>) -> anyhow::Result<(Self, Vec<String>)> {
        let cli_options = Self::cli_options();

        let path = match config_file {
            Some(p) => p,
            None => cli_options
                .config_file
                .as_ref()
                .ok_or_else(|| anyhow::anyhow!("Config file not specified"))?,
        };

        #[cfg(windows)]
        let file_patch = {
            use crate::platform::windows::crypto::decrypt_dpapi_config_file;
            use windows_dpapi::Scope::User;

            let content = if cli_options.enable_dpapi {
                tracing::info!("DPAPI decryption enabled for config file");
                decrypt_dpapi_config_file(path, User).map_err(|e| {
                    anyhow::anyhow!("Failed to decrypt DPAPI-protected config file: {e}")
                })?
            } else {
                tracing::debug!("Loading config file directly (no DPAPI)");
                tokio::fs::read_to_string(path).await?
            };
            serde_saphyr::from_str::<ConfigPatch>(&content)?
        };
        #[cfg(not(windows))]
        let file_patch = {
            let content = tokio::fs::read_to_string(path).await?;
            serde_saphyr::from_str::<ConfigPatch>(&content)?
        };

        let env_patch: ConfigPatch = serde_env::from_env_with_prefix("LW_CLIENT")?;
        let mut cli_patch = cli_options.clone();
        cli_patch.config_file = None;
        cli_patch.generate = None;

        let mut config = Config {
            config_file: path.to_path_buf(),
            ..Default::default()
        };

        let mut file_fields = String::new();
        let mut env_fields = String::new();
        let mut cli_fields = String::new();

        config.apply_with_log(file_patch, |field| {
            if field != "unknowns" {
                file_fields.push_str(&format!(", {field}"))
            }
        });
        config.apply_with_log(env_patch, |field| {
            if field != "unknowns" {
                env_fields.push_str(&format!(", {field}"))
            }
        });
        config.apply_with_log(cli_patch, |field| {
            if field != "unknowns" {
                cli_fields.push_str(&format!(", {field}"))
            }
        });

        let mut logs = Vec::new();
        if !file_fields.is_empty() {
            logs.push(format!("config file set: {}", &file_fields[2..]));
        }
        if !env_fields.is_empty() {
            logs.push(format!("environment var: {}", &env_fields[2..]));
        }
        if !cli_fields.is_empty() {
            logs.push(format!("commandline arg: {}", &cli_fields[2..]));
        }

        Ok((config, logs))
    }
}

// Note: it easier to see what is different from default in each validate testcase
#[allow(clippy::field_reassign_with_default)]
#[cfg(test)]
mod tests {
    use std::fs::read_to_string;
    use std::str::FromStr;

    use super::*;
    use regex::Regex;
    use schemars::SchemaGenerator;
    use test_case::test_case;

    #[test_case("../tests/client/client_config.yaml", true, 0)]
    #[test_case(
        "../tests/client/parallel_connect/client_config.tcp_then_udp.yaml",
        false,
        2
    )]
    #[test_case("../tests/client/parallel_connect/client_config.tcp.yaml", false, 10)]
    #[test_case(
        "../tests/client/parallel_connect/client_config.udp_then_tcp.yaml",
        false,
        2
    )]
    #[test_case("../tests/client/parallel_connect/client_config.udp.yaml", false, 10)]
    fn test_parse_config(config_file: &str, has_top_level_server: bool, servers_len: usize) {
        let matches =
            ConfigPatch::try_parse_from(["lightway-client", "--config-file", config_file]);
        let mut config = Config::default();
        let config_file = PathBuf::from_str(config_file).unwrap();
        let yaml_patch =
            serde_saphyr::from_str::<ConfigPatch>(&read_to_string(config_file).unwrap()).unwrap();
        config.apply(yaml_patch);
        config.apply(matches.unwrap());

        assert_eq!(config.server.is_empty(), !has_top_level_server);
        assert_eq!(config.servers.len(), servers_len);
    }

    #[cfg(desktop)]
    #[test]
    fn block_ipv6_defaults_on() {
        assert!(Config::default().block_ipv6);
    }

    #[cfg(desktop)]
    #[test_case(&["lightway-client"], true ; "absent keeps it on")]
    #[test_case(&["lightway-client", "--block-ipv6"], true ; "bare flag keeps it on")]
    #[test_case(&["lightway-client", "--block-ipv6", "false"], false ; "value turns it off")]
    #[test_case(&["lightway-client", "--block-ipv6=false"], false ; "equals form turns it off")]
    fn block_ipv6_from_cli(args: &[&str], expected: bool) {
        let mut config = Config::default();
        config.apply(ConfigPatch::try_parse_from(args).unwrap());
        assert_eq!(config.block_ipv6, expected);
    }

    #[cfg(desktop)]
    #[test_case("log_level: info", true ; "absent keeps it on")]
    #[test_case("block_ipv6: true", true ; "file keeps it on")]
    #[test_case("block_ipv6: false", false ; "file turns it off")]
    fn block_ipv6_from_file(yaml: &str, expected: bool) {
        let mut config = Config::default();
        config.apply(serde_saphyr::from_str::<ConfigPatch>(yaml).unwrap());
        assert_eq!(config.block_ipv6, expected);
    }

    fn get_byte_pattern() -> String {
        let schema = byte_size_schema(&mut SchemaGenerator::default());
        schema
            .get("pattern")
            .and_then(|v| v.as_str())
            .expect("pattern key must exist and be a string")
            .to_string()
    }

    #[test]
    fn valid_byte_size_input() {
        let re = Regex::new(&get_byte_pattern()).unwrap();
        for s in &["1KB", "1MB", "1GB", "1TB", "1PB", "1EB"] {
            assert!(
                re.is_match(s),
                "expected valid with si units uppercase input: {s}"
            );
        }
        for s in &["1KIB", "1MIB", "1GIB", "1TIB", "1PIB", "1EIB"] {
            assert!(
                re.is_match(s),
                "expected valid with iec units uppercase input: {s}"
            );
        }
        for s in &["1kb", "1mb", "1gb", "1tb", "1pb", "1eb"] {
            assert!(
                re.is_match(s),
                "expected valid with si units lowercase input: {s}"
            );
        }
        for s in &["1kib", "1mib", "1gib", "1tib", "1pib", "1eib"] {
            assert!(
                re.is_match(s),
                "expected valid with iec units lowercase input: {s}"
            );
        }
        for s in &["1.5KB", "0.5mb", "2.25GIB", "10.0tb"] {
            assert!(re.is_match(s), "expected valid with decimal input: {s}");
        }
        for s in &["1 KB", "10  MB", "1.5\tGIB", "100 tb"] {
            assert!(
                re.is_match(s),
                "expected valid with whitespace spacer input: {s}"
            );
        }
        for s in &["512MB", "1024KIB", "8gb"] {
            assert!(re.is_match(s), "expected valid with no spacer input: {s}");
        }
        for s in &["999999GB", "123456789TB", "1000000EIB"] {
            assert!(
                re.is_match(s),
                "expected valid with larger number input: {s}"
            );
        }
    }

    #[test]
    fn invalid_byte_size_input() {
        let re = Regex::new(&get_byte_pattern()).unwrap();
        assert!(!re.is_match(""), "empty string must not match");
        assert!(!re.is_match("1024"), "bare number must not match");
        for s in &["KB", "MIB", "gb"] {
            assert!(!re.is_match(s), "unit without number must not match: {s}");
        }
        for s in &["1B", "1YB", "1ZB", "1bit", "1byte", "1kbps"] {
            assert!(!re.is_match(s), "unknown unit must not match: {s}");
        }
        for s in &["1Kb", "1mB", "1Gib", "1tIb"] {
            assert!(!re.is_match(s), "mixed case must not match: {s}");
        }
        assert!(!re.is_match(".5KB"), "leading dot must not match");
        assert!(!re.is_match("1.2.3KB"), "multiple dots must not match");
        assert!(!re.is_match("-1KB"), "negative value must not match");
        for s in &["1KBs", "1MB/s", "1GIB "] {
            assert!(!re.is_match(s), "trailing content must not match: {s}");
        }
        for s in &["~1KB", "about 1MB", " 1GB"] {
            assert!(!re.is_match(s), "leading text must not match: {s}");
        }
        for s in &["1GB 512MB", "1TB1GB"] {
            assert!(
                !re.is_match(s),
                "multi-component byte size must not match: {s}"
            );
        }
    }

    #[test]
    fn validate_default_config() {
        let config = Config::default();
        assert!(config.validate().is_ok());
    }

    #[test]
    fn config_unknown_fields_cause_error() {
        let yaml = "unknown_field: true\n";
        let patch = serde_saphyr::from_str::<ConfigPatch>(yaml).expect("should parse");
        let mut config = Config::default();
        config.apply(patch);
        assert!(config.validate().is_err());
    }

    #[tracing_test::traced_test]
    #[test]
    fn config_unknown_fields_with_accept_flag_only_warns() {
        let yaml = "unknown_field: true\n";
        let patch = serde_saphyr::from_str::<ConfigPatch>(yaml).expect("should parse");
        let mut config = Config::default();
        config.accept_unknowns = true;
        config.apply(patch);
        assert!(config.validate().is_ok());
        assert!(logs_contain("unknown config fields will be ignored"));
    }

    #[cfg(not(macos))]
    #[tracing_test::traced_test]
    #[test]
    fn validate_sndbuf_on_tcp_server() {
        let mut config = Config::default();
        config.server = "127.0.0.1:27690".to_string();
        config.mode = ConnectionType::Tcp;
        config.sndbuf = ByteSize::mib(16);
        assert!(config.validate().is_ok());
        assert!(logs_contain(
            "sndbuf is set but cannot be applied to this TCP connections"
        ));
        assert!(logs_contain("127.0.0.1:27690"));
    }

    #[cfg(linux)]
    #[tracing_test::traced_test]
    #[test]
    fn validate_warns_on_low_tun_txqueuelen() {
        let mut config = Config::default();
        config.tun_txqueuelen = 500;
        assert!(config.validate().is_ok());
        assert!(logs_contain(
            "tun_txqueuelen is below the recommended minimum of 1000"
        ));
    }

    #[cfg(linux)]
    #[test]
    fn validate_rejects_zero_tun_txqueuelen() {
        let mut config = Config::default();
        config.tun_txqueuelen = 0;
        assert!(config.validate().is_err());
    }

    #[cfg(not(macos))]
    #[tracing_test::traced_test]
    #[test]
    fn validate_rcvbuf_on_tcp_server() {
        let mut config = Config::default();
        config.server = "127.0.0.1:27690".to_string();
        config.mode = ConnectionType::Tcp;
        config.rcvbuf = ByteSize::mib(16);
        assert!(config.validate().is_ok());
        assert!(logs_contain(
            "rcvbuf is set but cannot be applied to this TCP connections"
        ));
        assert!(logs_contain("127.0.0.1:27690"));
    }

    #[cfg(windows)]
    #[test]
    fn validate_device_guid() {
        let mut config = Config::default();
        config.device_guid = Some("550e8400-e29b-41d4-a716-446655440000".to_string());
        assert!(config.validate().is_ok());
        config.device_guid = Some("not-a-valid-uuid".to_string());
        assert!(config.validate().is_err());
    }

    #[tracing_test::traced_test]
    #[test]
    fn validate_pmtud_on_tcp_server() {
        let mut config = Config::default();
        config.server = "127.0.0.1:27690".to_string();
        config.enable_pmtud = true;
        config.mode = ConnectionType::Tcp;
        assert!(config.validate().is_ok());
        assert!(logs_contain(
            "enable_pmtud is set but cannot be applied to this TCP connections"
        ));
        assert!(logs_contain("127.0.0.1:27690"));
    }

    #[cfg(windows)]
    #[test]
    fn validate_wintun_ring_capacity() {
        let mut config = Config::default();
        config.wintun_ring_capacity = ByteSize::mib(3);
        assert!(config.validate().is_err());
    }
}
